<header class="header-wrapper">
    <nav class="header">
        <a class="menu-block" href="<?= $this->url('landing-page/home', array('action' => 'page', 'page' => 1)); ?>" class="menu-item"><?= $this->translate('Home') ?></a>
        <a class="menu-block" href="<?= $this->url('landing-page/default', ['action' => 'page']); ?>" class="menu-item"><?= $this->translate('Page1') ?></a>
    </nav>
</header>
