<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'error/404'                       => __DIR__ . '/view/error/404.phtml',
    'error/index'                     => __DIR__ . '/view/error/index.phtml',
    'landing-page/index/index'        => __DIR__ . '/view/landing-page/index/index.phtml',
    'landing-page/index/page'         => __DIR__ . '/view/landing-page/index/page.phtml',
    'layout-landing/layout_empty'     => __DIR__ . '/view/layout-landing/layout_empty.phtml',
    'layout-landing/layout_landing'   => __DIR__ . '/view/layout-landing/layout_landing.phtml',
    'layout-landing/_partials/footer' => __DIR__ . '/view/layout-landing/_partials/footer.phtml',
    'layout-landing/_partials/header' => __DIR__ . '/view/layout-landing/_partials/header.phtml',
);
